[package]
name = "Account"
version = "0.1.0"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework", rev = "devnet" }
Ownership = { git = "https://github.com/0xcapsules/capsules.git", subdir = "packages/ownership", rev = "master" }

[addresses]
sui_playground =  "0x0"